// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdIdFhcwFW0jUWYHoNoc7oBGag4xxSRyY',
    appId: '1:715728014325:web:5bbb00e35c19016683aebc',
    messagingSenderId: '715728014325',
    projectId: 'buildtrack-81b09',
    authDomain: 'buildtrack-81b09.firebaseapp.com',
    storageBucket: 'buildtrack-81b09.firebasestorage.app',
    measurementId: 'G-HQLDB5H5FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjdD2SfU5efpadq8oSB5PyplQrOVkNCpw',
    appId: '1:715728014325:android:eb4eabe6067fbdc883aebc',
    messagingSenderId: '715728014325',
    projectId: 'buildtrack-81b09',
    storageBucket: 'buildtrack-81b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFKB4U_NDsdceuTKX1yZo8IMnuH3bMFgk',
    appId: '1:715728014325:ios:2d674bd91f378a2083aebc',
    messagingSenderId: '715728014325',
    projectId: 'buildtrack-81b09',
    storageBucket: 'buildtrack-81b09.firebasestorage.app',
    iosBundleId: 'com.example.buildtrackMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFKB4U_NDsdceuTKX1yZo8IMnuH3bMFgk',
    appId: '1:715728014325:ios:2d674bd91f378a2083aebc',
    messagingSenderId: '715728014325',
    projectId: 'buildtrack-81b09',
    storageBucket: 'buildtrack-81b09.firebasestorage.app',
    iosBundleId: 'com.example.buildtrackMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdIdFhcwFW0jUWYHoNoc7oBGag4xxSRyY',
    appId: '1:715728014325:web:4f3b61dc6a1ff19083aebc',
    messagingSenderId: '715728014325',
    projectId: 'buildtrack-81b09',
    authDomain: 'buildtrack-81b09.firebaseapp.com',
    storageBucket: 'buildtrack-81b09.firebasestorage.app',
    measurementId: 'G-LZKCTTZTY1',
  );
}
